//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Old_Reader.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Old_Reader.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Reader.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure that you have set password in the settings page of Th Old Reader. As of now this is the only way to access the data..
        /// </summary>
        public static string steLoginExplanation {
            get {
                return ResourceManager.GetString("steLoginExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about....
        /// </summary>
        public static string strAboutMenu {
            get {
                return ResourceManager.GetString("strAboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a Windows Phone client for &quot;The Old Reader&quot;.
        ///To report bugs and feedback please click the following button..
        /// </summary>
        public static string strAboutText {
            get {
                return ResourceManager.GetString("strAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string strAboutTitle {
            get {
                return ResourceManager.GetString("strAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add Feed.
        /// </summary>
        public static string strAddFeed {
            get {
                return ResourceManager.GetString("strAddFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add feed.
        /// </summary>
        public static string strAddSubscription {
            get {
                return ResourceManager.GetString("strAddSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trevor /u/alexandertrevor for UI improvements.
        /// </summary>
        public static string strCredits {
            get {
                return ResourceManager.GetString("strCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        public static string strDoneAppBarButton {
            get {
                return ResourceManager.GetString("strDoneAppBarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download older.
        /// </summary>
        public static string strDownloadOlder {
            get {
                return ResourceManager.GetString("strDownloadOlder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registered email.
        /// </summary>
        public static string strEMail {
            get {
                return ResourceManager.GetString("strEMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error!.
        /// </summary>
        public static string strErrorTitle {
            get {
                return ResourceManager.GetString("strErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to could not add the feed..
        /// </summary>
        public static string strFeeadAddError {
            get {
                return ResourceManager.GetString("strFeeadAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successfully added the feed but could not move to the selected folder..
        /// </summary>
        public static string strFeedMoveError {
            get {
                return ResourceManager.GetString("strFeedMoveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feed URL.
        /// </summary>
        public static string strFeedUrl {
            get {
                return ResourceManager.GetString("strFeedUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Subscriptions.
        /// </summary>
        public static string strGettingSubscriptionList {
            get {
                return ResourceManager.GetString("strGettingSubscriptionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Tags.
        /// </summary>
        public static string strGettingTagList {
            get {
                return ResourceManager.GetString("strGettingTagList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Unread Count.
        /// </summary>
        public static string strGettingUnreadCount {
            get {
                return ResourceManager.GetString("strGettingUnreadCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Unread Items.
        /// </summary>
        public static string strGettingUnreadItems {
            get {
                return ResourceManager.GetString("strGettingUnreadItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to go to settings and setup the e-mail address and password for The Old Reader.
        /// </summary>
        public static string strGoToSettings {
            get {
                return ResourceManager.GetString("strGoToSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keep unread.
        /// </summary>
        public static string strKeepUnread {
            get {
                return ResourceManager.GetString("strKeepUnread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string strLocal {
            get {
                return ResourceManager.GetString("strLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to credentials.
        /// </summary>
        public static string strLoginPage {
            get {
                return ResourceManager.GetString("strLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mark all read.
        /// </summary>
        public static string strMarkAllRead {
            get {
                return ResourceManager.GetString("strMarkAllRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no unread items here. Hurray!.
        /// </summary>
        public static string strNoUnreadItems {
            get {
                return ResourceManager.GetString("strNoUnreadItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string strPassword {
            get {
                return ResourceManager.GetString("strPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to press back once more to exit.
        /// </summary>
        public static string strPressBackToExit {
            get {
                return ResourceManager.GetString("strPressBackToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sure?.
        /// </summary>
        public static string strPressBackToExitTitle {
            get {
                return ResourceManager.GetString("strPressBackToExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string strRefreshAppButton {
            get {
                return ResourceManager.GetString("strRefreshAppButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove saved.
        /// </summary>
        public static string strRemoveLocal {
            get {
                return ResourceManager.GetString("strRemoveLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save for later.
        /// </summary>
        public static string strSaveLocal {
            get {
                return ResourceManager.GetString("strSaveLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send feedback....
        /// </summary>
        public static string strSendFeedbackBtnText {
            get {
                return ResourceManager.GetString("strSendFeedbackBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings....
        /// </summary>
        public static string strSettingsMenu {
            get {
                return ResourceManager.GetString("strSettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share.
        /// </summary>
        public static string strShare {
            get {
                return ResourceManager.GetString("strShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show all posts.
        /// </summary>
        public static string strShowAllPosts {
            get {
                return ResourceManager.GetString("strShowAllPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show only unread.
        /// </summary>
        public static string strShowUnreadOnly {
            get {
                return ResourceManager.GetString("strShowUnreadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to old reader status....
        /// </summary>
        public static string strStatusMenu {
            get {
                return ResourceManager.GetString("strStatusMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriptions.
        /// </summary>
        public static string strSubscriptions {
            get {
                return ResourceManager.GetString("strSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Enter the Feed URL and press sync to preview the feed contents&lt;/b&gt;.
        /// </summary>
        public static string strSyncBrowserPrompt {
            get {
                return ResourceManager.GetString("strSyncBrowserPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sync.
        /// </summary>
        public static string strSyncButton {
            get {
                return ResourceManager.GetString("strSyncButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to target Folder.
        /// </summary>
        public static string strTargetFolder {
            get {
                return ResourceManager.GetString("strTargetFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} day(s) ago.
        /// </summary>
        public static string strTimeStrDays {
            get {
                return ResourceManager.GetString("strTimeStrDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hour(s) ago.
        /// </summary>
        public static string strTimeStrHours {
            get {
                return ResourceManager.GetString("strTimeStrHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        public static string strTimeStrNow {
            get {
                return ResourceManager.GetString("strTimeStrNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string strTimeStrUnknown {
            get {
                return ResourceManager.GetString("strTimeStrUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version.
        /// </summary>
        public static string strVersionStr {
            get {
                return ResourceManager.GetString("strVersionStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view full.
        /// </summary>
        public static string strViewFull {
            get {
                return ResourceManager.GetString("strViewFull", resourceCulture);
            }
        }
    }
}
