//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Old_Reader.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Old_Reader.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Reader.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure that you have set password in the settings page of The Old Reader. As of now this is the only way to access the data..
        /// </summary>
        public static string steLoginExplanation {
            get {
                return ResourceManager.GetString("steLoginExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about....
        /// </summary>
        public static string strAboutMenu {
            get {
                return ResourceManager.GetString("strAboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a Windows Phone client for &quot;The Old Reader&quot;.
        ///To report bugs and feedback please click the following button..
        /// </summary>
        public static string strAboutText {
            get {
                return ResourceManager.GetString("strAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string strAboutTitle {
            get {
                return ResourceManager.GetString("strAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add Feed.
        /// </summary>
        public static string strAddFeed {
            get {
                return ResourceManager.GetString("strAddFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to additional items to download when downloading old items.
        /// </summary>
        public static string strAdditionalDownloadCount {
            get {
                return ResourceManager.GetString("strAdditionalDownloadCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add feed.
        /// </summary>
        public static string strAddSubscription {
            get {
                return ResourceManager.GetString("strAddSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Items on top.
        /// </summary>
        public static string strAllItemsOnTop {
            get {
                return ResourceManager.GetString("strAllItemsOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app settings.
        /// </summary>
        public static string strAppSettingsPage {
            get {
                return ResourceManager.GetString("strAppSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to unsubscribe from {0}?.
        /// </summary>
        public static string strConfirmUnsubscribe {
            get {
                return ResourceManager.GetString("strConfirmUnsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trevor /u/alexandertrevor for UI improvements
        ////u/DatDoodKwan for French translation
        ////u/diogenesl for pt-br translation
        ////u/yudayyy for Bahasa Indonesia translation.
        /// </summary>
        public static string strCredits {
            get {
                return ResourceManager.GetString("strCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        public static string strDoneAppBarButton {
            get {
                return ResourceManager.GetString("strDoneAppBarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download older.
        /// </summary>
        public static string strDownloadOlder {
            get {
                return ResourceManager.GetString("strDownloadOlder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 days.
        /// </summary>
        public static string strDuration15Days {
            get {
                return ResourceManager.GetString("strDuration15Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one day.
        /// </summary>
        public static string strDuration1Day {
            get {
                return ResourceManager.GetString("strDuration1Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one month.
        /// </summary>
        public static string strDuration1Month {
            get {
                return ResourceManager.GetString("strDuration1Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one week.
        /// </summary>
        public static string strDuration1Week {
            get {
                return ResourceManager.GetString("strDuration1Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one year.
        /// </summary>
        public static string strDuration1Year {
            get {
                return ResourceManager.GetString("strDuration1Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to two months.
        /// </summary>
        public static string strDuration2Months {
            get {
                return ResourceManager.GetString("strDuration2Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to three months.
        /// </summary>
        public static string strDuration3Months {
            get {
                return ResourceManager.GetString("strDuration3Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to six months.
        /// </summary>
        public static string strDuration6Months {
            get {
                return ResourceManager.GetString("strDuration6Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days to keep the old feed cached on your device. more days mean more storage.
        /// </summary>
        public static string strDurationDescr {
            get {
                return ResourceManager.GetString("strDurationDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registered email.
        /// </summary>
        public static string strEMail {
            get {
                return ResourceManager.GetString("strEMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email....
        /// </summary>
        public static string strEMailMenuItem {
            get {
                return ResourceManager.GetString("strEMailMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error!.
        /// </summary>
        public static string strErrorTitle {
            get {
                return ResourceManager.GetString("strErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to could not add the feed..
        /// </summary>
        public static string strFeeadAddError {
            get {
                return ResourceManager.GetString("strFeeadAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successfully added the feed but could not move to the selected folder..
        /// </summary>
        public static string strFeedMoveError {
            get {
                return ResourceManager.GetString("strFeedMoveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feed URL.
        /// </summary>
        public static string strFeedUrl {
            get {
                return ResourceManager.GetString("strFeedUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting starred items.
        /// </summary>
        public static string strGettingStarredItems {
            get {
                return ResourceManager.GetString("strGettingStarredItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Subscriptions.
        /// </summary>
        public static string strGettingSubscriptionList {
            get {
                return ResourceManager.GetString("strGettingSubscriptionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Tags.
        /// </summary>
        public static string strGettingTagList {
            get {
                return ResourceManager.GetString("strGettingTagList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Unread Count.
        /// </summary>
        public static string strGettingUnreadCount {
            get {
                return ResourceManager.GetString("strGettingUnreadCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Unread Items.
        /// </summary>
        public static string strGettingUnreadItems {
            get {
                return ResourceManager.GetString("strGettingUnreadItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to go to settings and setup the e-mail address and password for The Old Reader.
        /// </summary>
        public static string strGoToSettings {
            get {
                return ResourceManager.GetString("strGoToSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keep unread.
        /// </summary>
        public static string strKeepUnread {
            get {
                return ResourceManager.GetString("strKeepUnread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string strLocal {
            get {
                return ResourceManager.GetString("strLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mark all read.
        /// </summary>
        public static string strMarkAllRead {
            get {
                return ResourceManager.GetString("strMarkAllRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to move.
        /// </summary>
        public static string strMenuMove {
            get {
                return ResourceManager.GetString("strMenuMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unsubscribe.
        /// </summary>
        public static string strMenuUnsubscribe {
            get {
                return ResourceManager.GetString("strMenuUnsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to move from.
        /// </summary>
        public static string strMoveFrom {
            get {
                return ResourceManager.GetString("strMoveFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to move feed.
        /// </summary>
        public static string strMoveSubscriptionPage {
            get {
                return ResourceManager.GetString("strMoveSubscriptionPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to move to.
        /// </summary>
        public static string strMoveTo {
            get {
                return ResourceManager.GetString("strMoveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no unread items here. Hurray!.
        /// </summary>
        public static string strNoUnreadItems {
            get {
                return ResourceManager.GetString("strNoUnreadItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open in ie....
        /// </summary>
        public static string strOpenInIE {
            get {
                return ResourceManager.GetString("strOpenInIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string strPassword {
            get {
                return ResourceManager.GetString("strPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to press back once more to exit.
        /// </summary>
        public static string strPressBackToExit {
            get {
                return ResourceManager.GetString("strPressBackToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sure?.
        /// </summary>
        public static string strPressBackToExitTitle {
            get {
                return ResourceManager.GetString("strPressBackToExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate app.
        /// </summary>
        public static string strRateApp {
            get {
                return ResourceManager.GetString("strRateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string strRefreshAppButton {
            get {
                return ResourceManager.GetString("strRefreshAppButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove saved.
        /// </summary>
        public static string strRemoveLocal {
            get {
                return ResourceManager.GetString("strRemoveLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save for later.
        /// </summary>
        public static string strSaveLocal {
            get {
                return ResourceManager.GetString("strSaveLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send feedback....
        /// </summary>
        public static string strSendFeedbackBtnText {
            get {
                return ResourceManager.GetString("strSendFeedbackBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings....
        /// </summary>
        public static string strSettingsMenu {
            get {
                return ResourceManager.GetString("strSettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share.
        /// </summary>
        public static string strShare {
            get {
                return ResourceManager.GetString("strShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show all posts.
        /// </summary>
        public static string strShowAllPosts {
            get {
                return ResourceManager.GetString("strShowAllPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show read items.
        /// </summary>
        public static string strShowReadItems {
            get {
                return ResourceManager.GetString("strShowReadItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show only unread.
        /// </summary>
        public static string strShowUnreadOnly {
            get {
                return ResourceManager.GetString("strShowUnreadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starred.
        /// </summary>
        public static string strStarredItemsLabel {
            get {
                return ResourceManager.GetString("strStarredItemsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to old reader status....
        /// </summary>
        public static string strStatusMenu {
            get {
                return ResourceManager.GetString("strStatusMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriptions.
        /// </summary>
        public static string strSubscriptions {
            get {
                return ResourceManager.GetString("strSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Enter the Feed URL and press sync to preview the feed contents&lt;/b&gt;.
        /// </summary>
        public static string strSyncBrowserPrompt {
            get {
                return ResourceManager.GetString("strSyncBrowserPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sync.
        /// </summary>
        public static string strSyncButton {
            get {
                return ResourceManager.GetString("strSyncButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to target Folder.
        /// </summary>
        public static string strTargetFolder {
            get {
                return ResourceManager.GetString("strTargetFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} day(s) ago.
        /// </summary>
        public static string strTimeStrDays {
            get {
                return ResourceManager.GetString("strTimeStrDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hour(s) ago.
        /// </summary>
        public static string strTimeStrHours {
            get {
                return ResourceManager.GetString("strTimeStrHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        public static string strTimeStrNow {
            get {
                return ResourceManager.GetString("strTimeStrNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string strTimeStrUnknown {
            get {
                return ResourceManager.GetString("strTimeStrUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed to unsubscribe from {0}!.
        /// </summary>
        public static string strUnsubscribeFailed {
            get {
                return ResourceManager.GetString("strUnsubscribeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update for the application is available in the marketplace. Do you want to update now?.
        /// </summary>
        public static string strUpdateAppMsgBody {
            get {
                return ResourceManager.GetString("strUpdateAppMsgBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available!.
        /// </summary>
        public static string strUpdateAppMsgTitle {
            get {
                return ResourceManager.GetString("strUpdateAppMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version.
        /// </summary>
        public static string strVersionStr {
            get {
                return ResourceManager.GetString("strVersionStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view full.
        /// </summary>
        public static string strViewFull {
            get {
                return ResourceManager.GetString("strViewFull", resourceCulture);
            }
        }
    }
}
